#!/bin/bash
# Quick Diagnostic Checklist for Add Expense Button Issue

echo "════════════════════════════════════════════════════════════"
echo "🔍 EXPENZO - Add Expense Button Diagnostics"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📋 CHECKLIST:"
echo ""
echo "1️⃣  Dev Server Running?"
echo "    [ ] npm run dev is running at http://localhost:5173/"
echo ""
echo "2️⃣  Browser Open?"
echo "    [ ] Opened http://localhost:5173/ in browser"
echo "    [ ] Page loaded successfully (no red errors)"
echo ""
echo "3️⃣  DevTools Console Open?"
echo "    [ ] Pressed F12 or Ctrl+Shift+I"
echo "    [ ] Switched to 'Console' tab"
echo ""
echo "4️⃣  Logged In?"
echo "    [ ] Entered username (e.g., 'TestUser')"
echo "    [ ] Clicked Login button"
echo "    [ ] See Dashboard with balance card"
echo ""
echo "5️⃣  Fill Form Fields?"
echo "    [ ] Clicked on 'Expense Description' field"
echo "    [ ] Typed: Groceries"
echo "    [ ] Clicked on 'Amount' field"  
echo "    [ ] Typed: 100"
echo ""
echo "6️⃣  Click Button?"
echo "    [ ] Clicked '+ Add Expense' button"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "🔎 WHAT TO LOOK FOR IN CONSOLE:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📝 Input Changes (as you type):"
echo "   Description input changed to: G"
echo "   Description input changed to: Gr"
echo "   Description input changed to: Gro"
echo "   ..."
echo "   Amount input changed to: 1"
echo "   Amount input changed to: 10"
echo "   Amount input changed to: 100"
echo ""
echo "✅ After Clicking Button (SHOULD see):"
echo "   🔍 Add Expense clicked - description: \"Groceries\" amount: \"100\""
echo "   🔍 Parsed amount: 100"
echo "   ✅ Adding expense: {description: \"Groceries\", amountNum: 100}"
echo "   📝 Dashboard received expense: {...}"
echo "   💾 Saved expenses for user \"TestUser\": [{...}]"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "❌ COMMON PROBLEMS:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Problem 1: No console messages at all"
echo "  → Hard refresh: Ctrl+Shift+R"
echo "  → Make sure HMR updated the code"
echo ""
echo "Problem 2: Only 'Add Expense clicked' but nothing after"
echo "  → Validation failed: Did you fill BOTH fields?"
echo "  → Check if you see ❌ warning in console"
echo ""
echo "Problem 3: All logs appear but NO expense shows"
echo "  → Check if Expense History list exists"
echo "  → Scroll the expense list"
echo "  → Try adding another expense"
echo ""
echo "Problem 4: Red error in console"
echo "  → Copy the error message"
echo "  → Share it for debugging"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "✅ WORKING STATE:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "When everything works:"
echo "  ✓ All console logs appear"
echo "  ✓ Expense appears in 'Expense History' list"
echo "  ✓ Balance updates"
echo "  ✓ Refresh page → Data persists"
echo ""
echo "════════════════════════════════════════════════════════════"
